{{- if not .Values.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  {{- if .Values.database.password }}
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  DB_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.user }}
  DB_USER: {{ .Values.database.user | b64enc | quote }}
  {{- else }}
  DB_USER: {{ "root" | b64enc | quote }}
  {{- end }}
  {{- if .Values.database.name }}
  DB_NAME: {{ .Values.database.name | b64enc | quote }}
  {{- else }}
  DB_NAME: {{ "mydatabase" | b64enc | quote }}
  {{- end }}
  DB_PORT: {{ "3306" | b64enc | quote }}
{{- end }}