{{- if .Values.vault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "gif-app.fullname" . }}-vault-database
  labels:
    {{- include "gif-app.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.vault.address | quote }}
    roleName: {{ .Values.vault.database.roleName | quote }}
    objects: |
      - objectName: "db-user"
        secretPath: "{{ .Values.vault.database.secretPath }}"
        secretKey: "DB_USER"
      - objectName: "db-password"
        secretPath: "{{ .Values.vault.database.secretPath }}"
        secretKey: "DB_PASSWORD"
      - objectName: "db-name"
        secretPath: "{{ .Values.vault.database.secretPath }}"
        secretKey: "DB_NAME"
      - objectName: "db-port"
        secretPath: "{{ .Values.vault.database.secretPath }}"
        secretKey: "DB_PORT"
  secretObjects:
    - secretName: {{ include "gif-app.fullname" . }}-mysql-secrets
      type: Opaque
      data:
        - objectName: "db-user"
          key: DB_USER
        - objectName: "db-password"
          key: DB_PASSWORD
        - objectName: "db-name"
          key: DB_NAME
        - objectName: "db-port"
          key: DB_PORT
{{- end }}