apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gifapp-vault-database
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc.cluster.local:8200"
    roleName: "flask-app"
    objects: |
      - objectName: "db-user"
        secretPath: "gifapp/data/database"
        secretKey: "DB_USER"
      - objectName: "db-password"
        secretPath: "gifapp/data/database"
        secretKey: "DB_PASSWORD"
      - objectName: "db-name"
        secretPath: "gifapp/data/database"
        secretKey: "DB_NAME"
      - objectName: "db-port"
        secretPath: "gifapp/data/database"
        secretKey: "DB_PORT"
  secretObjects:
    - secretName: gifapp-mysql-secrets
      type: Opaque
      data:
        - objectName: "db-user"
          key: DB_USER
        - objectName: "db-password"
          key: DB_PASSWORD
        - objectName: "db-name"
          key: DB_NAME
        - objectName: "db-port"
          key: DB_PORT
