apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: mysql
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      {{- if .Values.vault.enabled }}
      serviceAccountName: {{ .Values.vault.serviceAccount }}
      volumes:
        - name: secrets-store-db
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: gifapp-vault-database
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
        - name: init-sql
          configMap:
            name: {{ .Release.Name }}-mysql-init-sql
      {{- else }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
        - name: init-sql
          configMap:
            name: {{ .Release.Name }}-mysql-init-sql
      {{- end }}
      initContainers:
        - name: remove-lost-found
          image: busybox
          command: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          {{- if .Values.vault.enabled }}
          volumeMounts:
            - name: secrets-store-db
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          {{- else }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d
          {{- end }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-secrets
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_DATABASE
              value: {{ .Values.database.name | quote }}
          ports:
            - containerPort: {{ .Values.mysql.service.port }}
              name: mysql
