# Application Configuration
flask:
  image:
    repository: orelneto/flaskapp_with_db_motogpgif
    tag: 1.0.69
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 80
    targetPort: 5000
  replicas: 2

mysql:
  image:
    repository: mysql
    tag: 5.7
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  replicas: 1
  persistence:
    enabled: true
    storageClass: "managed-premium"
    size: 10Gi
  
# Database Configuration
database:
  name: mydatabase
  user: root
  password: rootpassword
  rootHost: "%"

# ConfigMaps and Init Scripts
initScript:
  enabled: true

# Ingress Configuration
ingress:
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gifapp.example.com
      paths:
        - path: /
          pathType: Prefix

# Vault Integration
vault:
  enabled: true  # הפוך ל-true כאשר מוכן להשתמש ב-Vault
  address: "http://vault.vault.svc.cluster.local:8200"
  serviceAccount: "flask-app-sa"
  database:
    secretPath: "gifapp/database"
    roleName: "flask-app"
  cicd:
    secretPath: "gifapp/cicd"
    roleName: "cicd-app"
  azure:
    secretPath: "gifapp/azure"
    roleName: "cicd-app"