apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-flask
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
    - port: http
      interval: 15s