grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
    nodePort: 30000
  persistence:
    enabled: true
    storageClassName: "hostpath"
    size: 1Gi

prometheus:
  prometheusSpec:
    retention: 15d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: hostpath
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
  service:
    type: NodePort
    nodePort: 30090

alertmanager:
  enabled: true
  service:
    type: NodePort
    nodePort: 30093
  
nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true