apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gifapp-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: flask-app
  endpoints:
  - port: http
    path: /metrics
  namespaceSelector:
    matchNames:
    - gifapp