apiVersion: v1
data:
  DB_HOST: mysql
  DB_NAME: mydatabase
  DB_PORT: "3306"
  FLASK_ENV: development
  PORT: "5000"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"DB_HOST":"mysql","DB_NAME":"mydatabase","DB_PORT":"3306","FLASK_ENV":"development","PORT":"5000"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"flask-config","namespace":"default"}}
  creationTimestamp: "2025-02-08T23:45:37Z"
  name: flask-config
  namespace: default
  resourceVersion: "711"
  uid: 646de8dd-3c9e-40b8-a3ec-05891003a8cd
