name: CI Pipeline

on:
  repository_dispatch:
    types: [start-ci-pipeline]
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:  # מאפשר הפעלה ידנית

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract Branch Name & Set Build Number
      shell: bash
      run: |
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        echo "VERSION=1.0.${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

    - name: Build Docker Image
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: mysql
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        PORT: ${{ secrets.PORT }}
      run: |
        # Debug: Print environment variables (mask sensitive data)
        echo "DB_HOST=$DB_HOST"
        echo "DB_PORT=$DB_PORT"
        echo "DB_NAME=$DB_NAME"
        echo "PORT=$PORT"
        echo "Using build version: ${{ env.VERSION }}"
        
        # Build the image with build arguments
        docker build \
          --build-arg DB_USER=$DB_USER \
          --build-arg DB_PASSWORD=$DB_PASSWORD \
          --build-arg DB_HOST=$DB_HOST \
          --build-arg DB_PORT=$DB_PORT \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg PORT=$PORT \
          -t orelneto/flaskapp_with_db_motogpgif:${{ env.VERSION }} ./src

    - name: Setup and Test Application
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: mysql
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        PORT: ${{ secrets.PORT }}
      run: |
        # Create a test docker-compose.yml file
        cat > ./src/docker-compose.test.yml << EOL
        version: '3'
        services:
          app:
            image: orelneto/flaskapp_with_db_motogpgif:${{ env.VERSION }}
            ports:
              - "5005:5000"
            environment:
              - FLASK_ENV=development
              - DB_USER=${DB_USER}
              - DB_PASSWORD=${DB_PASSWORD}
              - DB_HOST=mysql
              - DB_PORT=3306
              - DB_NAME=${DB_NAME}
            depends_on:
              mysql:
                condition: service_healthy
          mysql:
            image: mysql:5.7
            environment:
              MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
              MYSQL_DATABASE: ${DB_NAME}
              MYSQL_USER: ${DB_USER}
              MYSQL_PASSWORD: ${DB_PASSWORD}
            ports:
              - "3306:3306"
            healthcheck:
              test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p\${MYSQL_ROOT_PASSWORD}"]
              interval: 5s
              timeout: 5s
              retries: 10
        EOL
        
        # Copy init.sql to src directory if it's not there
        if [ ! -f ./src/init.sql ] && [ -f ./init.sql ]; then
          cp ./init.sql ./src/init.sql
        fi
        
        # Run the application with docker compose (notice no hyphen)
        cd src
        docker compose -f docker-compose.test.yml up -d
        
        # Wait for the application to start
        echo "Waiting for application to start..."
        sleep 60
        
        # Check if containers are running
        docker ps
        
        # Show logs of the containers to diagnose any issues
        echo "MySQL container logs:"
        docker compose -f docker-compose.test.yml logs mysql
        
        echo "App container logs:"
        docker compose -f docker-compose.test.yml logs app
        
        # Try to test the endpoint
        if curl -s -f http://localhost:5005; then
          echo "Application test successful!"
        else
          echo "Curl test failed, but continuing with the pipeline..."
        fi
        
        # Stop containers regardless of test result
        docker compose -f docker-compose.test.yml down

    - name: Push Docker image to DockerHub
      run: |
        # Tag images
        docker tag orelneto/flaskapp_with_db_motogpgif:${{ env.VERSION }} orelneto/flaskapp_with_db_motogpgif:latest
        
        # Push images
        docker push orelneto/flaskapp_with_db_motogpgif:${{ env.VERSION }}
        docker push orelneto/flaskapp_with_db_motogpgif:latest
        echo "Docker images pushed successfully"

    - name: Update Helm Chart Version
      run: |
        echo "Updating Helm chart version to ${{ env.VERSION }}"
        sed -i "s/version: .*/version: ${{ env.VERSION }}/" ./helm/gif-app/Chart.yaml
        sed -i "s/appVersion: .*/appVersion: \"${{ env.VERSION }}\"/" ./helm/gif-app/Chart.yaml
        
        # Update image tag in values.yaml
        sed -i "s/tag: .*/tag: ${{ env.VERSION }}/" ./helm/gif-app/values.yaml
        
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.12.0'
        
    - name: Package Helm Chart
      run: |
        mkdir -p ./helm-packages
        helm package ./helm/gif-app -d ./helm-packages
        echo "Helm chart packaged as gif-app-${{ env.VERSION }}.tgz"

    - name: Configure Git for GitHub Pages
      run: |
        git config --global user.name "OrelNeto-DO"
        git config --global user.email "orelnetodoazure@gmail.com"
        
    - name: Checkout Helm Charts Repository
      uses: actions/checkout@v3
      with:
        repository: OrelNeto-DO/helm-charts
        token: ${{ secrets.GH_PAT }}
        path: helm-repo
        
    - name: Update Helm Repository
      run: |
        # Copy the packaged chart to the repo directory
        cp ./helm-packages/gif-app-${{ env.VERSION }}.tgz helm-repo/
        
        # Update the index
        cd helm-repo
        helm repo index . --url https://OrelNeto-DO.github.io/helm-charts
        
        # Commit and push changes
        git add .
        git commit -m "Update GifApp Helm chart to version ${{ env.VERSION }}"
        git push

    - name: Trigger CD Pipeline
      if: success()
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.GH_PAT }}
        event-type: start-cd-pipeline
        client-payload: '{"version": "${{ env.VERSION }}"}'